domain: example.com

log:
  level: debug
  pretty: true

# support postgresql, mariadb, sqlite, mysql
database:
  type: postgresql
  url: postgres://hotaru:hotaru@127.0.0.1/hotaru

  # mariadb
  # type: mariadb
  # url: hotaru:hotaru@/hotaru

  # sqlite
  # type: sqlite
  # url: ./build/hotaru.db

# global:
#   # Rate limiting kicks in after the threshold
#   # number of "slots" have been taken by requests from a specific host. Each "slot"
#   # will be released after the cooloff time in milliseconds.
#   rate_limiting:
#     enabled: true
#     threshold: 20
#     cooloff_ms: 500
